### ISSUE TITLE
[front] checklist à vérifier

### ISSUE THREAD

**Issue by Laurence-Girault** [lluc/telemeta-integration#32]
**Technique : Perf**
- [ ] Rapidité d'affichage des pages : https://developers.google.com/speed/pagespeed/insights/
- [ ] Perf : https://www.webpagetest.org/
- [ ] Perf : https://www.dareboost.com/fr/home
- [ ] Perf environnemental : http://www.ecoindex.fr/
- [ ] Accessibilité : http://www.evaluera.co.uk/
- [ ] Sécurité : http://www.unmaskparasites.com/

**Technique**

- [ ] W3C : https://html5.validator.nu/
- [ ] Page 404
- [ ] Style print
- [ ] S'assurer qu'il n'y ai pas d'URL en dur dans les fichiers
- [ ] CSS et JS minifié
- [ ] Plus aucun test dans le backoffice et dans les DEV
- [ ] Page Mentions légales
- [ ] Aucune CSS n'est chargé sans utilités (attention à bootstrap)
- [ ] Les images sont ### optimisés
